version: "3.9"
services:
    iiko:
      container_name: iiko
      build:
         context: ./iiko
      env_file:
        - ./iiko/.env
      volumes:
        - ./static:/data/iiko
      command: bash -c "cp ./favorite.png /data/iiko && ts-node ./src/polling.ts"
      networks:
        - mongodb
networks:
  mongodb:
    external:
      name: main_gateway    
