version: '3'
networks:
  main_gateway:
    name: main_gateway
    driver: bridge
services:
  react:
    build:
      context: ./client
    stdin_open: true
    environment:
      - WDS_SOCKET_PORT=80
    container_name: react
    volumes:
      - "./client:/usr/app/cx"
      - "/usr/app/cx/node_modules"
    networks:
      - main_gateway
    ports:
      - 3000:3000
    cpus: 0.5
  nestjs:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    stdin_open: true
    depends_on:
      - redis
      - mongodb
    container_name: nestjs
    volumes:
      - "./server:/usr/app/cx"
    networks:
      - main_gateway
    cpus: 0.5
  redis:
    image: redis
    networks:
      - main_gateway
    mem_limit: 256m
    cpus: 0.5
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./mongo/data:/data/db
    networks:
      - main_gateway
    mem_limit: 512m
    cpus: 0.5
    
  nginx:
    container_name: nginx
    image: nginx:1.21.6-alpine
    depends_on:
      - nestjs
      - react
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./static:/etc/static
    networks:
      - main_gateway
    ports:
      - 80:80