version: "3.9"
networks:
    mongodb_net:
        driver: bridge
services:
    deliverycx_client:
        container_name: deliverycx_client
        build:
            context: ./client
        volumes:
          - ./client/build:/build
    deliverycx_backend:
        container_name: deliverycx_backend
        env_file:
            - ./server/.production.env
        depends_on:
            - redis
            - mongodb
        build:
            context: ./server
        networks:
          - mongodb_net
        links:
            - redis
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
          - ./client/build:/var/www/client
        networks:
          - mongodb_net
    redis:
        image: redis
        command:
            - "redis-server"
            - "--loglevel ${REDIS_LOGLEVEL:-warning}"
            - "--databases 2"
            - "--save 900 1"
            - "--save 300 10"
            - "--save 60 10000"
        volumes:
            - ./redis/data:/data
        networks:
          - mongodb_net
    mongodb:
        container_name: mongodb
        image: mongo
        volumes:
            - ./mongo/data:/data/db
        networks:
          - mongodb_net
