FROM node:16.13.1 as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./client .

RUN npm install
RUN npm install react-scripts@3.4.1 -g --silent

RUN npm run build

FROM nginx

COPY --from=build /app/build /var/www/client
COPY nginx/nginx.conf /etc/nginx/

EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]