version: "3.9"
networks:
    mongodb_net:
        name: deliverycx_nest_mongodb_net
        driver: bridge
services:
    deliverycx_client:
        container_name: deliverycx_client
        build:
            context: .
            dockerfile: ./Dockerfile.webserver
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - deliverycx_backend
        volumes:
          - ./static:/static
          - ./dhparam:/etc/nginx/dhparam
          - ./certbot/conf/:/etc/nginx/ssl/:ro
          - ./certbot/data:/var/www/letsencrypt
          - ./nginx/logs/access:/var/logs/nginx_access.log
          - ./nginx/logs/error:/var/logs/nginx_error.log
        networks:
          - mongodb_net
    deliverycx_backend:
        container_name: deliverycx_backend
        env_file:
            - ./server/.production.env
        depends_on:
            - redis
            - mongodb
        build:
            context: ./server
        networks:
          - mongodb_net
        links:
            - redis
        ports:
            - "5000:5000"
    redis:
        image: redis
        command:
            - "redis-server"
            - "--loglevel ${REDIS_LOGLEVEL:-warning}"
            - "--databases 2"
            - "--save 900 1"
            - "--save 300 10"
            - "--save 60 10000"
        volumes:
            - ./redis/data:/data
        networks:
          - mongodb_net
    mongodb:
        container_name: mongodb
        image: mongo
        volumes:
            - ./mongo/data:/data/db
        networks:
            - mongodb_net
    certbot:
        image: certbot/certbot
        command: certonly --webroot --webroot-path=/var/www/letsencrypt --email kirill_shkarun@mail.ru --agree-tos --no-eff-email -d xn--e1aybc.xn--80apgfh0ct5a.xn--p1ai
        volumes:
            - ./certbot/logs/:/var/log/letsencrypt
            - ./certbot/conf/:/etc/letsencrypt/:rw
            - ./certbot/data:/var/www/letsencrypt