FROM node:16.13.1 as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./client .

RUN npm install

RUN npm run build

FROM nginx

COPY --from=build /app/build /etc/app/cx/build
RUN mkdir /etc/app/cx/logs
COPY nginx/nginx.conf /etc/nginx/

EXPOSE 80