export enum InjectTokenEnum {
    "SEND_CODE_SERVICE" = "SEND_CODE_SERVICE",
    "REGISTER_SERVICE" = "REGISTER_SERVICE",
    "UPDATE_OPTIONS_SERVICE" = "UPDATE_OPTIONS_SERVICE",
    "USER" = "User"
}
